export const area = [[{
    label: '港島全區',
    value: '港島全區',
    checked: false
}, {
    label: '中半山',
    value: '中半山',
    checked: false
}, {
    label: '薄扶林',
    value: '薄扶林',
    checked: false
}, {
    label: '中上環',
    value: '中上環',
    checked: false
}, {
    label: '西環',
    value: '西環',
    checked: false
}], [{
    label: '九龍全區',
    value: '九龍全區',
    checked: false
}, {
    label: '中半山',
    value: '中半山',
    checked: false
}, {
    label: '薄扶林',
    value: '薄扶林',
    checked: false
}, {
    label: '中上環',
    value: '中上環',
    checked: false
}, {
    label: '西環',
    value: '西環',
    checked: false
}], [{
    label: '新界全區',
    value: '新界全區',
    checked: false
}, {
    label: '中半山',
    value: '中半山',
    checked: false
}, {
    label: '薄扶林',
    value: '薄扶林',
    checked: false
}, {
    label: '中上環',
    value: '中上環',
    checked: false
}, {
    label: '西環',
    value: '西環',
    checked: false
}]];
