export const OtherSubject = [{
    label: '游水（蛙式）',
    value: '游水（蛙式）',
    checked: false,
}, {
    label: '游水（自由式）',
    value: '游水（自由式）',
    checked: false
}, {
    label: '游水（背泳）',
    value: '游水（背泳）',
    checked: false
}, {
    label: '游水（蝶式）',
    value: '游水（蝶式）',
    checked: false
}, {
    label: '繪畫',
    value: '繪畫',
    checked: false
}, {
    label: '電腦',
    value: '電腦',
    checked: false
}, {
    label: '劍橋英語',
    value: '劍橋英語',
    checked: false
}, {
    label: '奧數',
    value: '奧數',
    checked: false
}, {
    label: '珠心算',
    value: '珠心算',
    checked: false
}, {
    label: '學林數學',
    value: '學林數學',
    checked: false
}, {
    label: 'IGCSE',
    value: 'IGCSE',
    checked: false
}, {
    label: 'IB',
    value: 'IB',
    checked: false
}];
