export const subject = [{
    label: '全科',
    value: '全科',
    checked: false,
    text: '可授：全科'
}, {
    label: '理科',
    value: '理科',
    checked: false,
    text: '可授：理科'
}, {
    label: '數學',
    value: '數學',
    checked: false,
    text: '可授：數學'
}, {
    label: '文科',
    value: '文科',
    checked: false,
    text: '可授：文科'
}, {
    label: '英語',
    value: '英語',
    checked: false,
    text: '可授：英語'
}, {
    label: '地理',
    value: '地理',
    checked: false,
    text: '可授：地理'
}, {
    label: '中文',
    value: '中文',
    checked: false,
    text: '可授：中文'
}, {
    label: '商科',
    value: '商科',
    checked: false,
    text: '可授：商科'
}, {
    label: '數學（M1）',
    value: '數學（M1）',
    checked: false,
    text: '可授：數學（M1）'
}, {
    label: '數學（M2）',
    value: '數學（M2）',
    checked: false,
    text: '可授：數學（M2）'
}, {
    label: '綜合人民學',
    value: '綜合人民學',
    checked: false,
    text: '可授：綜合人民學'
}, {
    label: '中國文學',
    value: '中國文學',
    checked: false,
    text: '可授：中國文學'
}, {
    label: '英國文學',
    value: '英國文學',
    checked: false,
    text: '可授：英國文學'
}, {
    label: '應用數學',
    value: '應用數學',
    checked: false,
    text: '可授：應用數學'
}, {
    label: '中國歷史',
    value: '中國歷史',
    checked: false,
    text: '可授：中國歷史'
}, {
    label: '世界歷史',
    value: '世界歷史',
    checked: false,
    text: '可授：世界歷史'
}, {
    label: '化學',
    value: '化學',
    checked: false,
    text: '可授：化學'
}, {
    label: '通識教育',
    value: '通識教育',
    checked: false,
    text: '可授：通識教育'
}, {
    label: '綜合科學',
    value: '綜合科學',
    checked: false,
    text: '可授：綜合科學'
}, {
    label: '經濟',
    value: '經濟',
    checked: false,
    text: '可授：經濟'
}, {
    label: '附加數學',
    value: '附加數學',
    checked: false,
    text: '可授：附加數學'
}, {
    label: '純粹數學',
    value: '純粹數學',
    checked: false,
    text: '可授：純粹數學'
}, {
    label: '數學及統計學',
    value: '數學及統計學',
    checked: false,
    text: '可授：數學及統計學'
}, {
    label: '物理',
    value: '物理',
    checked: false,
    text: '可授：物理'
}, {
    label: '生物',
    value: '生物',
    checked: false,
    text: '可授：生物'
}, {
    label: '商業學',
    value: '商業學',
    checked: false,
    text: '可授：商業學'
}, {
    label: '會計',
    value: '會計',
    checked: false,
    text: '可授：會計'
}, {
    label: '企業概論',
    value: '企業概論',
    checked: false,
    text: '可授：企業概論'
}, {
    label: '政府及公共事務',
    value: '政府及公共事務',
    checked: false,
    text: '可授：政府及公共事務'
}, {
    label: 'BAFS',
    value: 'BAFS',
    checked: false,
    text: '可授：BAFS'
}];
