export const subject = [{
    label: '全科',
    value: '全科',
    checked: false
}, {
    label: '理科',
    value: '理科',
    checked: false
}, {
    label: '數學',
    value: '數學',
    checked: false
}, {
    label: '文科',
    value: '文科',
    checked: false
}, {
    label: '英語',
    value: '英語',
    checked: false
}, {
    label: '地理',
    value: '地理',
    checked: false
}, {
    label: '中文',
    value: '中文',
    checked: false
}, {
    label: '商科',
    value: '商科',
    checked: false
}, {
    label: '數學（M1）',
    value: '數學（M1）',
    checked: false
}, {
    label: '數學（M2）',
    value: '數學（M2）',
    checked: false
}, {
    label: '綜合人民學',
    value: '綜合人民學',
    checked: false
}, {
    label: '中國文學',
    value: '中國文學',
    checked: false
}, {
    label: '英國文學',
    value: '英國文學',
    checked: false
}, {
    label: '應用數學',
    value: '應用數學',
    checked: false
}, {
    label: '中國歷史',
    value: '中國歷史',
    checked: false
}, {
    label: '世界歷史',
    value: '世界歷史',
    checked: false
}, {
    label: '化學',
    value: '化學',
    checked: false
}, {
    label: '通識教育',
    value: '通識教育',
    checked: false
}, {
    label: '綜合科學',
    value: '綜合科學',
    checked: false
}, {
    label: '經濟',
    value: '經濟',
    checked: false
}, {
    label: '附加數學',
    value: '附加數學',
    checked: false
}, {
    label: '純粹數學',
    value: '純粹數學',
    checked: false
}, {
    label: '數學及統計學',
    value: '數學及統計學',
    checked: false
}, {
    label: '物理',
    value: '物理',
    checked: false
}, {
    label: '生物',
    value: '生物',
    checked: false
}, {
    label: '商業學',
    value: '商業學',
    checked: false
}, {
    label: '會計',
    value: '會計',
    checked: false
}, {
    label: '企業概論',
    value: '企業概論',
    checked: false
}, {
    label: '政府及公共事務',
    value: '政府及公共事務',
    checked: false
}, {
    label: 'BAFS',
    value: 'BAFS',
    checked: false
}];
