export const College = [{
    label: '--未有就讀大學--',
    value: '--未有就讀大學--'
}, {
    label: '香港大學',
    value: '香港大學'
}, {
    label: '香港中文大學',
    value: '香港中文大學'
}, {
    label: '香港理工大學',
    value: '香港理工大學'
}, {
    label: '香港城市大學',
    value: '香港城市大學'
}, {
    label: '香港浸會大學',
    value: '香港浸會大學'
}, {
    label: '香港科技大學',
    value: '香港科技大學'
}, {
    label: '嶺南大學',
    value: '嶺南大學'
}, {
    label: '香港教育學院',
    value: '香港教育學院'
}, {
    label: '香港公開大學',
    value: '香港公開大學'
}, {
    label: '香港樹仁大學',
    value: '香港樹仁大學'
}, {
    label: '香港演藝學院',
    value: '香港演藝學院'
}, {
    label: '珠海書院',
    value: '珠海書院'
}, {
    label: '香港專業教育學院',
    value: '香港專業教育學院'
}];
