export const HK2 = [{
        label: '<港島區全部>',
        value: '<港島區全部>',
        isLeaf: true
    }, {
        label: '中半山',
        value: '中半山',
        isLeaf: true
    }, {
        label: '薄扶林',
        value: '薄扶林',
        isLeaf: true
    }, {
        label: '中上環',
        value: '中上環',
        isLeaf: true
    }, {
        label: '西環',
        value: '西環',
        isLeaf: true
    }, {
        label: '灣仔',
        value: '灣仔',
        isLeaf: true
    }, {
        label: '銅鑼灣',
        value: '銅鑼灣',
        isLeaf: true
    }, {
        label: '跑馬地',
        value: '跑馬地',
        isLeaf: true
    }, {
        label: '北角',
        value: '北角',
        isLeaf: true
    }, {
        label: '則魚涌及太古',
        value: '則魚涌及太古',
        isLeaf: true
    }, {
        label: '筲箕灣及西灣河',
        value: '筲箕灣及西灣河',
        isLeaf: true
    }, {
        label: '柴灣及小西灣',
        value: '柴灣及小西灣',
        isLeaf: true
    }, {
        label: '香港仔',
        value: '香港仔',
        isLeaf: true
    }, {
        label: '鴨利洲',
        value: '鴨利洲',
        isLeaf: true
    }, {
        label: '赤柱',
        value: '赤柱',
        isLeaf: true
}, {
        label: '<九龍區全部>',
        value: '<九龍區全部>',
        isLeaf: true
    }, {
        label: '藍田及油塘',
        value: '藍田及油塘',
        isLeaf: true
    }, {
        label: '秀茂坪',
        value: '秀茂坪',
        isLeaf: true
    }, {
        label: '觀塘',
        value: '觀塘',
        isLeaf: true
    }, {
        label: '牛頭角及九龍灣',
        value: '牛頭角及九龍灣',
        isLeaf: true
    }, {
        label: '彩虹及牛池灣',
        value: '彩虹及牛池灣',
        isLeaf: true
    }, {
        label: '慈雲山',
        value: '慈雲山',
        isLeaf: true
    }, {
        label: '鑽石山,新蒲崗及黃大仙',
        value: '鑽石山,新蒲崗及黃大仙',
        isLeaf: true
    }, {
        label: '樂富',
        value: '樂富',
        isLeaf: true
    }, {
        label: '九龍塘',
        value: '九龍塘',
        isLeaf: true
    }, {
        label: '石硤尾',
        value: '石硤尾',
        isLeaf: true
    }, {
        label: '何文田',
        value: '何文田',
        isLeaf: true
    }, {
        label: '九龍城',
        value: '九龍城',
        isLeaf: true
    }, {
        label: '土瓜灣',
        value: '土瓜灣',
        isLeaf: true
    }, {
        label: '紅磡',
        value: '紅磡',
        isLeaf: true
    }, {
        label: '油麻地,佐敦及尖沙咀',
        value: '油麻地,佐敦及尖沙咀',
        isLeaf: true
    }, {
        label: '油麻地',
        value: '油麻地',
        isLeaf: true
    }, {
        label: '佐敦',
        value: '佐敦',
        isLeaf: true
    }, {
        label: '尖沙咀',
        value: '尖沙咀',
        isLeaf: true
    }, {
        label: '旺角及旺角西',
        value: '旺角及旺角西',
        isLeaf: true
    }, {
        label: '大角咀',
        value: '大角咀',
        isLeaf: true
    }, {
        label: '深水步',
        value: '深水步',
        isLeaf: true
    }, {
        label: '長沙灣',
        value: '長沙灣',
        isLeaf: true
    }, {
        label: '荔枝角',
        value: '荔枝角',
        isLeaf: true
    }, {
        label: '美孚',
        value: '美孚',
        isLeaf: true
}, {
        label: '<新界區全部>',
        value: '<新界區全部>',
        isLeaf: true
    }, {
        label: '將軍澳',
        value: '將軍澳',
        isLeaf: true
    }, {
        label: '西貢',
        value: '西貢',
        isLeaf: true
    }, {
        label: '荃灣',
        value: '荃灣',
        isLeaf: true
    }, {
        label: '葵涌,葵芳及青衣',
        value: '葵涌,葵芳及青衣',
        isLeaf: true
    }, {
        label: '葵涌及葵芳',
        value: '葵涌及葵芳',
        isLeaf: true
    }, {
        label: '青衣',
        value: '青衣',
        isLeaf: true
    }, {
        label: '荔景站',
        value: '荔景站',
        isLeaf: true
    }, {
        label: '沙田大圍',
        value: '沙田大圍',
        isLeaf: true
    }, {
        label: '沙田市中心',
        value: '沙田市中心',
        isLeaf: true
    }, {
        label: '沙田小瀝源',
        value: '沙田小瀝源',
        isLeaf: true
    }, {
        label: '沙田火炭',
        value: '沙田火炭',
        isLeaf: true
    }, {
        label: '沙田馬鞍山',
        value: '沙田馬鞍山',
        isLeaf: true
    }, {
        label: '大埔',
        value: '大埔',
        isLeaf: true
    }, {
        label: '粉嶺及上水',
        value: '粉嶺及上水',
        isLeaf: true
    }, {
        label: '粉嶺',
        value: '粉嶺',
        isLeaf: true
    }, {
        label: '上水',
        value: '上水',
        isLeaf: true
    }, {
        label: '元朗及天水圍',
        value: '元朗及天水圍',
        isLeaf: true
    }, {
        label: '屯門',
        value: '屯門',
        isLeaf: true
    }, {
        label: '離島(除東涌)',
        value: '離島(除東涌)',
        isLeaf: true
    }, {
        label: '青龍頭',
        value: '青龍頭',
        isLeaf: true
    }, {
        label: '深井',
        value: '深井',
        isLeaf: true
    }, {
        label: '馬灣',
        value: '馬灣',
        isLeaf: true
    }, {
        label: '東涌',
        value: '東涌',
        isLeaf: true
}];
